### ISSUE TITLE
获取用户性别时男性用户有些返回为未知

### ISSUE THREAD

**Issue by ChenXu233** [noneplugin/nonebot-plugin-userinfo#31]
环境：
nonebot2.3.3
plugin-userinfo0.2.6
napcat2.6

调用方法：
```python
get_user_info(bot, event, id, use_cache=False)
```
预期结果：
性别为男的用户返回user_gender为male

实际结果：
返回unkown

已经排除上游napcat的问题了，详见这个[issue](https://github.com/ChenXu233/nonebot_plugin_dialectlist/issues/38)

**Comment by MeetWq** [comment]
userinfo 优先调用 get_group_member_info，可以看看这个接口的结果是否有问题

**Comment by ChenXu233** [comment]
![image](https://github.com/user-attachments/assets/9219ad60-9598-43c4-b276-0837099e9c51)
get_group_member_info接口是异常的，可能真的是napcat的问题，我去更新一下napcat

**Comment by ChenXu233** [comment]
更新napcat后到目前都没有再复现。
