### ISSUE TITLE
[提问]是否可以获取指定usr_id用户的信息

### ISSUE THREAD

**Issue by Agnes4m** [noneplugin/nonebot-plugin-userinfo#7]
例如提供当前适配器平台下的某用户的user_id，也能按照这个格式获取信息

**Comment by MeetWq** [comment]
这个插件就是做这个的呀 。。

**Comment by MeetWq** [comment]
只不过并不是所有适配器都能获取的到任意 user_id 的信息，比如 tg 只能是当前群组成员

**Comment by Agnes4m** [comment]
是我没仔细看。因为参考readme给出的示例，只看到注释是获取当前事件对象和bot对象的信息。

第一个示例中的event.get_user_id()换成事件对应平台的用户id，就可以获取指定对象了没错吧

**Comment by MeetWq** [comment]
是的
